Agrega primer versión de QuadratTableReader
IslasGECI/distdens pull request #3
Opened 2019-09-17 18:18 UTC by nepito

Agregeremos pruebas que sea tengan el 100% de cobertura resistentes a mutaciones.

2019-11-26 22:36 UTC, islasfernando reviewed
Ya lo corrí en mi compu, y todo funciona bien

2019-11-26 22:36 UTC, islasfernando commented on Dockerfile
> +RUN pip install --requirement requirements.txt
No conviene pasar los requerimientos acá?

2019-11-27 04:00 UTC, evaristor commented on Dockerfile
> +RUN pip install --requirement requirements.txt
Sí, definitivamente

2020-01-23 18:53 UTC, devarops requested changes
Creo que conviene eliminar el `.travis.yml` ya que ahora tenemos el `actions.yml`

2020-01-23 18:57 UTC, evaristor commented on Dockerfile
> +RUN pip install numpy \
```suggestion
RUN pip install \
    numpy \
```

2020-02-14 21:33 UTC, devarops approved these changes

2020-02-14 21:34 UTC, closed without merging