Agrega función fillout
IslasGECI/distdens pull request #6
Opened 2020-05-28 16:26 UTC by evaristor

Esta función la usamos en [`muestreo-aves-marinas-ipbc`](https://bitbucket.org/IslasGECI/muestreo-aves-marinas-ipbc/)

2020-05-28 16:38 UTC, islasfernando approved these changes

2020-05-28 16:57 UTC, nepito requested changes
Hay 40 mutantes sobrevivientes. Por favor atrápenlos...

2020-06-09 18:54 UTC, evaristor commented
Quedan 9 mutantes
![image](https://user-images.githubusercontent.com/3461018/84188096-e59ea200-aa47-11ea-8dd7-3577be1419c3.png)

2020-06-19 18:56 UTC, evaristor commented
Quedan 4 mutantes.

![image](https://user-images.githubusercontent.com/3461018/85171472-f0b1b900-b223-11ea-82e1-c7010ca09356.png)

2020-06-26 01:12 UTC, evaristor commented
> Hay 40 mutantes sobrevivientes. Por favor atrápenlos...

Listo, @nepito 

![image](https://user-images.githubusercontent.com/3461018/85810260-55cb4a00-b70f-11ea-9df6-2bab34c7fed7.png)

2020-06-30 16:32 UTC, nepito requested changes
Aquí está mi comentarios @evaristor

2020-06-30 16:32 UTC, nepito commented on distdens/fillout.py
> +    x_cerrada = np.concatenate(
Por favor refactoriza en una función las líneas 13-19, pues es código repetido:
```suggestion
    x_cerrada = close_coordinate(x, indice_pegado_costa)
```

2020-06-30 16:32 UTC, nepito commented on distdens/fillout.py
> +    y_cerrada = np.concatenate(
Por favor refactoriza en una función las líneas 20-26, pues es código repetido:
```suggestion
    y_cerrada = close_coordinate(y, indice_pegado_costa)
```

2020-06-30 16:32 UTC, nepito commented on tests/test_QuadratTableReader.py
> +    "Zona_utm": ["11R", "11R", "11R"],
Qué loco que esté teminando con una coma, ¿no?

2020-06-30 16:32 UTC, nepito commented on Makefile
> +codecov_token = eae768b1-8c32-40a8-89fd-6b7589f9efa8
¿Para qué usamos esto y cómo lo obtenemos?

2020-06-30 17:01 UTC, evaristor commented
Gracias por tu revisión @nepito

2020-07-06 18:50 UTC, evaristor commented on distdens/fillout.py
> +    x_cerrada = np.concatenate(
Muchas gracias por hacer la prueba para refactorizar, @nepito. Eso es más de la mitad del trabajo.

2020-07-06 19:10 UTC, evaristor commented on Makefile
> +codecov_token = eae768b1-8c32-40a8-89fd-6b7589f9efa8
Nos muestra [esta información](https://codecov.io/gh/IslasGECI/distdens/compare/88817052a542964016fe33e817c0d94af71bb185...c18f03913267f0dad461400def51fbf7529409a9) adicional que por lo pronto podemos ignorar.
El _token_ lo obtenemos [aquí](https://codecov.io/gh/IslasGECI/distdens/settings).

2020-07-06 19:11 UTC, evaristor commented on distdens/fillout.py
> +    y_cerrada = np.concatenate(
Muchas gracias por hacer la prueba para refactorizar, @nepito. Eso es más de la mitad del trabajo.

2020-07-06 19:14 UTC, evaristor commented on tests/test_QuadratTableReader.py
> +    "Zona_utm": ["11R", "11R", "11R"],
Quité la coma del final

2020-07-06 19:26 UTC, evaristor commented on tests/test_QuadratTableReader.py
> +    "Zona_utm": ["11R", "11R", "11R"],
Pero el Black se la regresó

2020-07-07 17:31 UTC, nepito requested changes
Listo @evaristor te dejé una prueba fallando para sugerirte una refactorizada

2020-07-07 17:31 UTC, nepito commented on Makefile
> +codecov_token = eae768b1-8c32-40a8-89fd-6b7589f9efa8
muchas gracias @evaristor ya se lo agregué al repo con el que estoy trabajando

2020-07-07 17:31 UTC, nepito commented on distdens/fillout.py
> +    x_prueba = np.concatenate(
Por favor refactoriza las líneas 8-9 y 15-24 para que la 15 quedara algo así:
```suggestion
    x_prueba = _testing(limits[0:2], closed_x)
```
Creo que el nombre no es el correcto, pero no supe el objetivo de la función.

2020-07-07 17:31 UTC, nepito commented on distdens/fillout.py
> +    y_prueba = np.concatenate(
Por favor refactoriza las líneas 10-11 y 25-34 para que la 25 quedara algo así:
```suggestion
    y_prueba = _testing(limits[2:4], closed_y)
```

2020-07-07 17:33 UTC, evaristor commented
Gracias por tu revisión, @nepito

2020-07-14 20:34 UTC, evaristor commented
> Listo @evaristor te dejé una prueba fallando para sugerirte una refactorizada

@nepito No encontré la prueba fallando que me dejaste. ¿La pushaste o me la dejaste en tu máquina?

2020-07-14 20:58 UTC, nepito commented
> > Listo @evaristor te dejé una prueba fallando para sugerirte una refactorizada
> 
> @nepito No encontré la prueba fallando que me dejaste. ¿La pushaste o me la dejaste en tu máquina?

Aquí la había dejado. La acabo de _pushar_ ojalá te sirva

2020-07-31 15:39 UTC, nepito approved these changes
La aprobamos en un tomate @islasfernando  y @nepito

2020-07-31 15:39 UTC, merged